# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501

import typing

from nautilus_trader import model

__all__ = [
    "EodhdDataClientConfig",
    "EodhdDataClientFactory",
    "EodhdDataLoader",
]

@typing.final
class EodhdDataClientConfig:
    def __init__(
        self,
        api_key: str | None = None,
        http_base_url: str | None = None,
        proxy_url: str | None = None,
        exchange: str | None = None,
        poll_interval_secs: int | None = None,
        backfill_days: int | None = None,
        price_precision: int | None = None,
        currency: str | None = None,
        timeout_secs: int | None = None,
        load_instruments: bool | None = None,
        bulk_exchanges: typing.Sequence[str] | None = None,
        load_corporate_actions: bool | None = None,
        ws_base_url: str | None = None,
        streaming: bool | None = None,
    ) -> None: ...
    @property
    def has_api_key(self) -> bool: ...
    @property
    def exchange(self) -> str: ...
    @property
    def poll_interval_secs(self) -> int: ...
    @property
    def backfill_days(self) -> int: ...
    @property
    def price_precision(self) -> int: ...
    @property
    def load_instruments(self) -> bool: ...
    @property
    def bulk_exchanges(self) -> list[str]: ...
    @property
    def load_corporate_actions(self) -> bool: ...
    @property
    def streaming(self) -> bool: ...

@typing.final
class EodhdDataClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...

@typing.final
class EodhdDataLoader:
    def __init__(
        self,
        api_key: str | None = None,
        base_url: str | None = None,
        currency: str | None = None,
        price_precision: int | None = None,
        timeout_secs: int | None = None,
        proxy_url: str | None = None,
    ) -> None: ...
    def api_key_masked(self) -> str: ...
    def instrument(self, ticker: str) -> typing.Any: ...
    def instruments(self, exchange: str) -> typing.Any: ...
    def bars(
        self, instrument_id: model.InstrumentId, start: str, end: str, period: str | None = None
    ) -> typing.Any: ...
    def corporate_actions(
        self, instrument_id: model.InstrumentId, start: str, end: str
    ) -> typing.Any: ...
