# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501

import typing

from nautilus_trader import model

__all__ = [
    "EodhdDataLoader",
]

@typing.final
class EodhdDataLoader:
    def __init__(
        self,
        api_key: str | None = None,
        base_url: str | None = None,
        currency: str | None = None,
        price_precision: int | None = None,
        timeout_secs: int | None = None,
        proxy_url: str | None = None,
    ) -> None: ...
    def api_key_masked(self) -> str: ...
    def instrument(self, ticker: str) -> typing.Any: ...
    def instruments(self, exchange: str) -> typing.Any: ...
    def bars(
        self, instrument_id: model.InstrumentId, start: str, end: str, period: str | None = None
    ) -> typing.Any: ...
