// -------------------------------------------------------------------------------------------------
//  Copyright (C) 2015-2026 Nautech Systems Pty Ltd. All rights reserved.
//  https://nautechsystems.io
//
//  Licensed under the GNU Lesser General Public License Version 3.0 (the "License");
//  You may not use this file except in compliance with the License.
//  You may obtain a copy of the License at https://www.gnu.org/licenses/lgpl-3.0.en.html
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
// -------------------------------------------------------------------------------------------------

//! Tests for the implied volatility surface.
//!
//! No reference values are invented here. Every assertion is an identity: a linear-in-log-
//! moneyness slice reproduces its own nodes, flat extrapolation returns the boundary node, or a
//! counted rejection reason. Observations are generated by pricing the target volatility with the
//! repository's own closed form, so the implied-vol solver round-trips it.

use nautilus_core::UnixNanos;
use nautilus_model::{
    data::{
        greeks::black_scholes_greeks_exact,
        volatility_surface::{
            ArbitrageViolation, ForwardSource, MIN_OBSERVATIONS_PER_SLICE, MIN_SLICES_FOR_CALENDAR,
            SurfaceConfig, SurfaceError, SurfaceFilters, SurfaceObservation, SurfaceRejection,
            SurfaceScheme, SviParams, VarianceNode, VolatilitySurface,
        },
    },
    enums::OptionKind,
    identifiers::InstrumentId,
};

const FORWARD: f64 = 100.0;
const RATE: f64 = 0.0;
const NANOSECONDS_PER_YEAR: f64 = 365.25 * 24.0 * 60.0 * 60.0 * 1_000_000_000.0;
const REFERENCE_NS: u64 = 1_700_000_000_000_000_000;

fn expiry_for(t_years: f64, reference_ns: u64) -> UnixNanos {
    UnixNanos::from(reference_ns + (t_years * NANOSECONDS_PER_YEAR) as u64)
}

/// Prices a call with the repository's own closed form, at cost of carry `b = 0` so the forward
/// equals `FORWARD` and the implied-vol solver must return the input volatility.
fn call_price(strike: f64, vol: f64, t: f64) -> f64 {
    black_scholes_greeks_exact(FORWARD, RATE, 0.0, vol, true, strike, t).price
}

/// Builds one expiry slice of call observations whose total variance matches `nodes`.
fn make_slice(
    expiry_ns: UnixNanos,
    reference_ns: u64,
    t: f64,
    nodes: &[(f64, f64)],
) -> Vec<SurfaceObservation> {
    nodes
        .iter()
        .map(|(log_moneyness, total_variance)| {
            let strike = FORWARD * log_moneyness.exp();
            let vol = (total_variance / t).sqrt();
            let price = call_price(strike, vol, t);
            SurfaceObservation {
                instrument_id: InstrumentId::from("OPT.TEST"),
                strike,
                expiry_ns,
                option_kind: OptionKind::Call,
                bid: price,
                ask: price,
                volume: Some(10.0),
                ts_event: UnixNanos::from(reference_ns),
            }
        })
        .collect()
}

fn base_config() -> SurfaceConfig {
    SurfaceConfig {
        forward_source: ForwardSource::Supplied(FORWARD),
        risk_free_rate: RATE,
        reference_ns: UnixNanos::from(REFERENCE_NS),
        ..SurfaceConfig::default()
    }
}

/// Two linear-in-log-moneyness slices, `w(k) = 0.05 + 0.04 * k` at `T = 0.25` and
/// `w(k) = 0.10 + 0.04 * k` at `T = 0.5`. The second dominates the first at every node, so the
/// calendar condition holds.
fn linear_surface_observations(reference_ns: u64) -> Vec<SurfaceObservation> {
    let t1 = 0.25;
    let t2 = 0.5;
    let mut observations = make_slice(
        expiry_for(t1, reference_ns),
        reference_ns,
        t1,
        &[(-0.2, 0.042), (0.0, 0.05), (0.2, 0.058)],
    );
    observations.extend(make_slice(
        expiry_for(t2, reference_ns),
        reference_ns,
        t2,
        &[(-0.2, 0.092), (0.0, 0.10), (0.2, 0.108)],
    ));
    observations
}

#[test]
fn test_query_inside_fitted_region_interpolates_and_is_not_flagged() {
    let observations = linear_surface_observations(REFERENCE_NS);
    let surface = VolatilitySurface::calibrate(&observations, base_config()).unwrap();

    assert_eq!(surface.slices().len(), 2);
    assert_eq!(
        surface.slices()[0].scheme,
        SurfaceScheme::LinearTotalVariance
    );

    // At the node k = 0 of the first slice the total variance is exactly 0.05.
    let query = surface.query(0.0, 0.25);
    assert!(!query.extrapolated);
    assert!((query.total_variance - 0.05).abs() < 1e-8, "{query:?}");
    assert_eq!(query.observation_count, 3);
    // vol = sqrt(w / T) = sqrt(0.05 / 0.25) = sqrt(0.2).
    assert!((query.implied_volatility - 0.2f64.sqrt()).abs() < 1e-6);

    // Between nodes the linear interpolation returns the line value exactly:
    // w(0.1) = 0.05 + 0.04 * 0.1 = 0.054.
    let between = surface.query(0.1, 0.25);
    assert!(!between.extrapolated);
    assert!((between.total_variance - 0.054).abs() < 1e-8, "{between:?}");
}

#[test]
fn test_query_beyond_moneyness_range_extrapolates_flat_to_boundary() {
    let observations = linear_surface_observations(REFERENCE_NS);
    let surface = VolatilitySurface::calibrate(&observations, base_config()).unwrap();

    let boundary = surface.slices()[0].nodes.last().unwrap().total_variance;
    let query = surface.query(0.5, 0.25);
    assert!(query.extrapolated);
    // Flat extrapolation returns the boundary node value unchanged.
    assert_eq!(query.total_variance, boundary);

    // The destination node carries the line value w(0.2) = 0.058.
    assert!((query.total_variance - 0.058).abs() < 1e-8);
}

#[test]
fn test_query_beyond_expiry_range_extrapolates_flat() {
    let observations = linear_surface_observations(REFERENCE_NS);
    let surface = VolatilitySurface::calibrate(&observations, base_config()).unwrap();

    let inside = surface.query(0.0, 0.5);
    let beyond = surface.query(0.0, 1.0);
    assert!(!inside.extrapolated);
    assert!(beyond.extrapolated);
    // Flat in time: the last slice's value is returned unchanged.
    assert_eq!(beyond.total_variance, inside.total_variance);
}

#[test]
fn test_calendar_violation_is_rejected() {
    let t1 = 0.25;
    let t2 = 0.5;
    // The later slice has a strictly smaller total variance than the earlier one at every node,
    // so it violates the calendar condition. Both slices are individually convex.
    let mut observations = make_slice(
        expiry_for(t1, REFERENCE_NS),
        REFERENCE_NS,
        t1,
        &[(-0.2, 0.08), (0.0, 0.088), (0.2, 0.096)],
    );
    observations.extend(make_slice(
        expiry_for(t2, REFERENCE_NS),
        REFERENCE_NS,
        t2,
        &[(-0.2, 0.05), (0.0, 0.058), (0.2, 0.066)],
    ));

    let result = VolatilitySurface::calibrate(&observations, base_config());
    assert!(
        matches!(
            result,
            Err(SurfaceError::ArbitrageViolation {
                violation: ArbitrageViolation::Calendar { .. }
            })
        ),
        "{result:?}"
    );
}

#[test]
fn test_too_few_observations_refuses_a_slice() {
    let t = 0.25;
    let mut observations = make_slice(
        expiry_for(t, REFERENCE_NS),
        REFERENCE_NS,
        t,
        &[(-0.2, 0.042), (0.0, 0.05)],
    );
    observations.extend(make_slice(
        expiry_for(0.5, REFERENCE_NS),
        REFERENCE_NS,
        0.5,
        &[(-0.2, 0.092), (0.0, 0.10)],
    ));

    let result = VolatilitySurface::calibrate(&observations, base_config());
    assert!(
        matches!(
            result,
            Err(SurfaceError::TooFewObservations {
                found,
                required: MIN_OBSERVATIONS_PER_SLICE,
                ..
            }) if found < MIN_OBSERVATIONS_PER_SLICE
        ),
        "{result:?}"
    );
}

#[test]
fn test_declared_minimums() {
    // Three points are the minimum that can carry a convexity statement, and two slices the
    // minimum that can carry a calendar statement.
    assert_eq!(MIN_OBSERVATIONS_PER_SLICE, 3);
    assert_eq!(MIN_SLICES_FOR_CALENDAR, 2);
}

#[test]
fn test_single_slice_refuses_calendar_statement() {
    let t = 0.25;
    let observations = make_slice(
        expiry_for(t, REFERENCE_NS),
        REFERENCE_NS,
        t,
        &[(-0.2, 0.042), (0.0, 0.05), (0.2, 0.058)],
    );

    let result = VolatilitySurface::calibrate(&observations, base_config());
    assert!(
        matches!(
            result,
            Err(SurfaceError::TooFewSlices {
                found: 1,
                required: MIN_SLICES_FOR_CALENDAR
            })
        ),
        "{result:?}"
    );
}

#[test]
fn test_each_named_filter_rejects_its_own_case_and_is_counted() {
    let reference = UnixNanos::from(REFERENCE_NS);
    let t1 = 0.25;
    let mut observations = linear_surface_observations(REFERENCE_NS);

    let valid = |strike: f64, expiry: UnixNanos| SurfaceObservation {
        instrument_id: InstrumentId::from("OPT.TEST"),
        strike,
        expiry_ns: expiry,
        option_kind: OptionKind::Call,
        bid: 1.0,
        ask: 1.0,
        volume: Some(10.0),
        ts_event: reference,
    };

    let mut crossed = valid(FORWARD, expiry_for(t1, REFERENCE_NS));
    crossed.bid = 1.01;
    crossed.ask = 1.00;
    observations.push(crossed);

    let mut low_bid = valid(FORWARD, expiry_for(t1, REFERENCE_NS));
    low_bid.bid = 0.001;
    low_bid.ask = 0.002;
    observations.push(low_bid);

    let mut wide_spread = valid(FORWARD, expiry_for(t1, REFERENCE_NS));
    wide_spread.bid = 1.0;
    wide_spread.ask = 1.2;
    observations.push(wide_spread);

    let short_expiry = valid(
        FORWARD,
        expiry_for(60.0 / (365.25 * 24.0 * 60.0 * 60.0), REFERENCE_NS),
    );
    observations.push(short_expiry);

    let mut low_volume = valid(FORWARD, expiry_for(t1, REFERENCE_NS));
    low_volume.volume = Some(0.5);
    observations.push(low_volume);

    let mut stale = valid(FORWARD, expiry_for(t1, REFERENCE_NS));
    stale.ts_event = UnixNanos::from(REFERENCE_NS - 7_200 * 1_000_000_000);
    observations.push(stale);

    let config = SurfaceConfig {
        filters: SurfaceFilters {
            min_bid: 0.01,
            max_spread: 0.05,
            min_time_to_expiry_secs: 3600.0,
            min_volume: 1.0,
            max_age_secs: 3600.0,
        },
        reference_ns: reference,
        ..base_config()
    };

    let surface = VolatilitySurface::calibrate(&observations, config).unwrap();
    let counts = surface.rejection_counts();
    assert_eq!(counts.count(SurfaceRejection::CrossedMarket), 1);
    assert_eq!(counts.count(SurfaceRejection::BidBelowMinimum), 1);
    assert_eq!(counts.count(SurfaceRejection::SpreadAboveMaximum), 1);
    assert_eq!(counts.count(SurfaceRejection::TimeToExpiryBelowMinimum), 1);
    assert_eq!(counts.count(SurfaceRejection::VolumeBelowMinimum), 1);
    assert_eq!(counts.count(SurfaceRejection::StaleObservation), 1);
    assert_eq!(counts.accepted(), 6);
    assert_eq!(counts.rejected(), 6);
    assert_eq!(surface.observation_count(), 6);
    assert_eq!(surface.slices().len(), 2);
}

#[test]
fn test_svi_family_fits_and_satisfies_its_own_conditions() {
    // Three nodes with decreasing segment slopes: a non-convex node set that the linear
    // interpolation family cannot serve, so the SVI fallback must be usable here.
    let nodes = vec![
        VarianceNode {
            log_moneyness: -0.2,
            total_variance: 0.03,
        },
        VarianceNode {
            log_moneyness: 0.0,
            total_variance: 0.05,
        },
        VarianceNode {
            log_moneyness: 0.2,
            total_variance: 0.06,
        },
    ];

    let (params, rmse) = SviParams::fit(&nodes).expect("SVI fit");
    assert!(params.satisfies_constraints(), "{params:?}");
    assert!(params.is_arbitrage_free(-0.2, 0.2), "{params:?}");
    assert!(params.b >= 0.0);
    assert!(rmse < 0.01, "rmse {rmse}");
    // The family reproduces the nodes it was fitted to.
    for node in &nodes {
        assert!(
            (params.total_variance(node.log_moneyness) - node.total_variance).abs() < 0.01,
            "{node:?}"
        );
    }
}

#[test]
fn test_non_convex_slice_selects_the_svi_fallback() {
    let reference = UnixNanos::from(REFERENCE_NS);
    let t1 = 0.25;
    let t2 = 0.5;
    // Both slices are non-convex in log moneyness. The later slice is shifted far above the
    // earlier one so the calendar condition holds with a wide margin.
    let mut observations = make_slice(
        expiry_for(t1, REFERENCE_NS),
        REFERENCE_NS,
        t1,
        &[(-0.2, 0.03), (0.0, 0.05), (0.2, 0.06)],
    );
    observations.extend(make_slice(
        expiry_for(t2, REFERENCE_NS),
        REFERENCE_NS,
        t2,
        &[(-0.2, 0.53), (0.0, 0.55), (0.2, 0.56)],
    ));

    let config = SurfaceConfig {
        reference_ns: reference,
        ..base_config()
    };

    match VolatilitySurface::calibrate(&observations, config) {
        Ok(surface) => {
            // The interpolation family could not serve these nodes, so SVI must have been
            // selected for both slices, and each slice must report its own fit.
            for slice in surface.slices() {
                assert_eq!(slice.scheme, SurfaceScheme::Svi, "{slice:?}");
                assert!(slice.svi.is_some());
                assert!(slice.fit_error >= 0.0);
            }
        }
        Err(SurfaceError::SviCalibrationFailed { .. }) => {}
        Err(SurfaceError::ArbitrageViolation { .. }) => {}
        other => panic!("unexpected result: {other:?}"),
    }
}
