# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501

import typing

__all__ = [
    "MoomooDataClientConfig",
    "MoomooDataClientFactory",
]

@typing.final
class MoomooDataClientConfig:
    def __init__(
        self,
        host: str | None = None,
        port: int | None = None,
        markets: typing.Sequence[str] | None = None,
        adjustment: str | None = None,
        session: str | None = None,
        book_depth: int | None = None,
        subscribe_trades: bool | None = None,
        subscribe_quotes: bool | None = None,
        snapshot_universe: bool | None = None,
        load_instruments: bool | None = None,
        timeout_secs: int | None = None,
    ) -> None: ...
    @property
    def host(self) -> str | None: ...
    @property
    def port(self) -> int | None: ...
    @property
    def resolved_host(self) -> str: ...
    @property
    def resolved_port(self) -> int: ...
    @property
    def markets(self) -> list[str]: ...
    @property
    def adjustment(self) -> str: ...
    @property
    def session(self) -> str: ...
    @property
    def book_depth(self) -> int: ...
    @property
    def subscribe_trades(self) -> bool: ...
    @property
    def subscribe_quotes(self) -> bool: ...
    @property
    def snapshot_universe(self) -> bool: ...
    @property
    def load_instruments(self) -> bool: ...
    @property
    def timeout_secs(self) -> int | None: ...

@typing.final
class MoomooDataClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...
